オプション課題:Rspec修正、let, traitの利用
knykd/rspec_app_exam pull request #1
Opened 2019-11-12 02:44 UTC by knykd

* FIXME --> テストが成功するよう修正
* TODO --> 記載事項に沿ってリファクタリング

* 実行結果(bundle exec rspec spec/system/task_spec.rb)
[![Image from Gyazo](https://i.gyazo.com/2f6a185087597ca435192be620e5b884.png)](https://gyazo.com/2f6a185087597ca435192be620e5b884)

2019-11-12 03:31 UTC, yuji91 commented on spec/system/task_spec.rb
> +        end
`switch_to_window(windows.last)`を記載して以降のpageの参照先を切り替える形式でも記載できます。(修正は必要ありません！)

2019-11-12 03:32 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(tds[2]).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
`strftime`ではなく、view側で使用している日付表示のメソッドを使って記載してみましょう。

2019-11-12 03:37 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(tds[0]).not_to have_content task.title
`expect(find)`を使った方が簡潔に記載できます！

2019-11-12 03:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +        change_task
`change_task`という名前より、「既にステータスが完了のタスク」のテストデータを作成することが分かる名前にした方が良いです。
traitは「そのテストデータがどの様な状態か」を示す様に設定できると良いです。
（active, inactive, with_xxx, without_xxxなど）
statusをdoneにする定義はtrait内に追加してしまいましょう。

2019-11-12 03:58 UTC, yuji91 requested changes
コメントしました！

2019-11-12 16:34 UTC, knykd commented on spec/system/task_spec.rb
> +        end
こちらcf51ddaで修正しました。

2019-11-12 16:35 UTC, knykd commented on spec/system/task_spec.rb
> +        expect(tds[2]).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
こちらcf51ddaで修正しました。

2019-11-12 16:36 UTC, knykd commented on spec/system/task_spec.rb
> +        expect(tds[0]).not_to have_content task.title
こちら501dca4で修正しました。

2019-11-12 16:36 UTC, knykd commented on spec/system/task_spec.rb
> +        change_task
こちら78e4974で修正しました。

2019-11-13 06:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(tds[2]).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
cf51dda の前後に半角スペースを開けるとリンクになります！

2019-11-13 06:46 UTC, yuji91 approved these changes
LGTM!

https://github.com/knykd/rspec_app_exam/pull/1#discussion_r345591548 だけ確認しておいて下さい。

2019-11-13 06:47 UTC, knykd commented on spec/system/task_spec.rb
> +        expect(tds[2]).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
78e4974

2019-11-14 07:04 UTC, merged